server:
    basePath: http://147.172.178.30:8080/stmgmt

db:
    synchronize: true
    dropSchema: true

logger:
    levels:
        - error
        - warn
        - debug
        - verbose
    requests: false
    dbErrors: true
